PARAM:
  I2C_ID_THUNDERBORG: 0x15
  I2C_SLAVE: 0x0703
  PWM_MAX: 255
  I2C_MAX_LEN: 6
  VOLTAGE_PIN_MAX: 36.3 # Maximum voltage from the analog voltage monitoring pin
  VOLTAGE_PIN_CORRECTION: 0.0 # Correction value for the analog voltage monitoring pin
  BATTERY_MIN_DEFAULT: 7.0 # Default minimum battery monitoring voltage
  BATTERY_MAX_DEFAULT: 35.0 # Default maximum battery monitoring voltage
  ANALOG_MAX: 0x3FF # Maximum value for analog readings

COMMAND:
  SET_LED1: 1 # Set the colour of the ThunderBorg LED
  GET_LED1: 2 # Get the colour of the ThunderBorg LED
  SET_LED2: 3 # Set the colour of the ThunderBorg Lid LED
  GET_LED2: 4 # Get the colour of the ThunderBorg Lid LED
  SET_LEDS: 5 # Set the colour of both the LEDs
  SET_LED_BATT_MON: 6 # Set the colour of both LEDs to show the current battery level
  GET_LED_BATT_MON: 7 # Get the state of showing the current battery level via the LEDs

  SET_A_FWD: 8 # Set motor A PWM rate in a forwards direction
  SET_A_REV: 9 # Set motor A PWM rate in a reverse direction
  GET_A: 10 # Get motor A direction and PWM rate
  SET_B_FWD: 11 # Set motor B PWM rate in a forwards direction
  SET_B_REV: 12 # Set motor B PWM rate in a reverse direction
  GET_B: 13 # Get motor B direction and PWM rate
  ALL_OFF: 14 # Switch everything off
  GET_DRIVE_A_FAULT: 15 # Get the drive fault flag for motor A, indicates faults such as short-circuits and under voltage
  GET_DRIVE_B_FAULT: 16 # Get the drive fault flag for motor B, indicates faults such as short-circuits and under voltage
  SET_ALL_FWD: 17 # Set all motors PWM rate in a forwards direction
  SET_ALL_REV: 18 # Set all motors PWM rate in a reverse direction
  SET_FAILSAFE: 19 # Set the failsafe flag, turns the motors off if communication is interrupted
  GET_FAILSAFE: 20 # Get the failsafe flag
  GET_BATT_VOLT: 21 # Get the battery voltage reading
  SET_BATT_LIMITS: 22 # Set the battery monitoring limits
  GET_BATT_LIMITS: 23 # Get the battery monitoring limits
  WRITE_EXTERNAL_LED: 24 # Write a 32bit pattern out to SK9822 / APA102C
  GET_ID: 0x99 # Get the board identifier
  SET_I2C_ADD: 0xAA # Set a new I2C address

  VALUE_FWD: 1 # I2C value representing forward
  VALUE_REV: 2 # I2C value representing reverse

  VALUE_ON: 1 # I2C value representing on
  VALUE_OFF: 0 # I2C value representing off
